name: CI/CD
 
on:
  push:
    branches:
      - develop # 更换为你的默认开发分支
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
 
      - name: Install Dependencies
        run: npm install
 
      - name: Build
        run: npm build --prod
 
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME}}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}  # 如果默认端口22不变可以省略
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}